### PR TITLE
Updates to readme and mastermind_pair.rb

### PR DESCRIPTION
**Pull request by MarchandMD**
small changes to the Readme markdown file and some minor changes to the `mastermind_pair.rb` file. 

I also re-organized the directory to follow the convention of using a `lib/` directory, as well as initialized RSpec, for testing

### CODE REVIEW

**Comment by MarchandMD** [comment]
Robert!  

Just spending a little bit of time with the project. Did some minor changes. Not sure what you have to do, other than to accept the pull request (PR).

**Comment by MarchandMD** [comment]
built out the input validation; tweaked the #play_round method;

**Comment by MarchandMD** [comment]
decided to add a board

**Comment by rsuazo** [comment]
nice work!  merged your updates!

**Comment by MarchandMD** [comment]
Thanks!

Was it pretty easy to merge? 

Did you look at the diffs?

**Pull request merged**
